default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: vue_redux_rails_development
test:
  <<: *default
  database: vue_redux_rails_test
production:
  <<: *default
  database: vue_redux_rails_production
